//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_Gestion_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier_Admission
    {
        public int ID_Admission { get; set; }
        public string Chirurgie_prog { get; set; }
        public Nullable<System.DateTime> date_admission { get; set; }
        public Nullable<System.DateTime> date_chirurgie { get; set; }
        public Nullable<System.DateTime> date_conge { get; set; }
        public string nss { get; set; }
        public Nullable<int> numero_lits { get; set; }
        public Nullable<int> ID_Medecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
