//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_Gestion_Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Info
    {
        public int ID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool doctor { get; set; }
        public bool orderly { get; set; }
        public bool admin { get; set; }
    }
}
